# Auto-generated by compose2nix

{ config, pkgs, lib, inputs,  ... }:

{

  #### Import secret
  age.secrets.yamtrack-secret = {
    file = ../../secrets/yamtrack-secret.age;
  };


  #### Ensure data directory exists
  systemd.tmpfiles.rules = [
    "d /srv/yamtrack/db 0750 _2b docker -"
  ];

  #### Docker runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };

  virtualisation.oci-containers.backend = "docker";

  #### Yamtrack container
  virtualisation.oci-containers.containers."yamtrack" = {
    image = "ghcr.io/fuzzygrim/yamtrack:latest";

    environment = {
      REDIS_URL    = "redis://redis:6379";
      REGISTRATION = "True";
      TZ           = "America/Vancouver";
      URLS         = "https://yamtrack.daikonsoft.ca";
    };

    #### Load SECRET from encrypted file
    environmentFiles = [
      config.age.secrets.yamtrack-secret.path
    ];

    # Database location
    volumes = [
      "/srv/yamtrack/db:/yamtrack/db:rw"
    ];

    ports = [
      "8000:8000/tcp"
    ];

    dependsOn = [
      "yamtrack-redis"
    ];

    log-driver = "journald";
    autoStart = false;

    extraOptions = [
      "--network-alias=yamtrack"
      "--network=yamtrack_default"
    ];
  };

  systemd.services."docker-yamtrack" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };

    after = [
      "docker-network-yamtrack_default.service"
    ];

    requires = [
      "docker-network-yamtrack_default.service"
    ];

    partOf   = [ "docker-compose-yamtrack-root.target" ];
    wantedBy = [ "docker-compose-yamtrack-root.target" ];
  };

  #### Redis container
  virtualisation.oci-containers.containers."yamtrack-redis" = {
    image = "redis:8-alpine";

    volumes = [
      "yamtrack_redis_data:/data:rw"
    ];

    log-driver = "journald";
    autoStart = false;

    extraOptions = [
      "--network-alias=redis"
      "--network=yamtrack_default"
    ];
  };

  systemd.services."docker-yamtrack-redis" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };

    after = [
      "docker-network-yamtrack_default.service"
      "docker-volume-yamtrack_redis_data.service"
    ];

    requires = [
      "docker-network-yamtrack_default.service"
      "docker-volume-yamtrack_redis_data.service"
    ];

    partOf   = [ "docker-compose-yamtrack-root.target" ];
    wantedBy = [ "docker-compose-yamtrack-root.target" ];
  };

  #### Docker network
  systemd.services."docker-network-yamtrack_default" = {
    path = [ pkgs.docker ];

    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f yamtrack_default";
    };

    script = ''
      docker network inspect yamtrack_default || docker network create yamtrack_default
    '';

    partOf   = [ "docker-compose-yamtrack-root.target" ];
    wantedBy = [ "docker-compose-yamtrack-root.target" ];
  };

  #### Docker volume
  systemd.services."docker-volume-yamtrack_redis_data" = {
    path = [ pkgs.docker ];

    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };

    script = ''
      docker volume inspect yamtrack_redis_data || docker volume create yamtrack_redis_data
    '';

    partOf   = [ "docker-compose-yamtrack-root.target" ];
    wantedBy = [ "docker-compose-yamtrack-root.target" ];
  };

  #### Root compose target
  systemd.targets."docker-compose-yamtrack-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix (Yamtrack)";
    };
  };

  #### Operator command
  environment.systemPackages = [
    (pkgs.writeShellScriptBin "yamtrack" ''
      set -euo pipefail

      ROOT_TARGET="docker-compose-yamtrack-root.target"
      UNIT="docker-yamtrack.service"

      usage() {
        echo "Usage: yamtrack {start|stop|restart|status|logs|update}"
        exit 1
      }

      case "''${1:-}" in
        start)
          echo "🐳 Starting Yamtrack..."
          sudo systemctl start "$ROOT_TARGET"
          echo "✅ Yamtrack started"
          echo "🌐 http://localhost:8000"
          ;;
        stop)
          echo "🛑 Stopping Yamtrack..."
          sudo systemctl stop "$ROOT_TARGET"
          echo "✅ Yamtrack stopped"
          ;;
        restart)
          echo "🔄 Restarting Yamtrack..."
          sudo systemctl restart "$ROOT_TARGET"
          echo "✅ Yamtrack restarted"
          ;;
        status)
          systemctl status "$ROOT_TARGET" \
            --no-pager \
            --plain \
            --full
          ;;
        logs)
          sudo journalctl -u "$UNIT" -f
          ;;
        update)
          echo "⬇️  Updating Yamtrack image..."
          sudo systemctl restart "$ROOT_TARGET"
          echo "✅ Update complete"
          ;;
        *)
          usage
          ;;
      esac
    '')
  ];
}
